config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :salesforces
  end
  resources :leads

  root 'admin/salesforces#index'

  resources :leads

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/salesforce.rb
class Admin::Salesforce < ActiveRecord::Base
end

app/models/lead.rb
class Lead < ActiveRecord::Base
  
  # Fields validation
  validates :name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
end

app/controllers/admin/salesforces_controller.rb
class Admin::SalesforcesController < ApplicationController
  before_action :set_admin_salesforce, only: [:show, :edit, :update, :destroy]
  # GET /admin/salesforces
  def index
    @admin_salesforces = Admin::Salesforce.all

    if(@admin_salesforces.count == 0)
      redirect_to action: "new"
    else
      redirect_to action: "edit", id: @admin_salesforces[0].id
    end

  end

  # GET /admin/salesforces/1
  def show
    begin
      @salesforce = Databasedotcom::Client.new(:client_id => @admin_salesforce.client_id, :client_secret => @admin_salesforce.client_secret)
      @salesforce.authenticate(:username => @admin_salesforce.username, :password => @admin_salesforce.password + @admin_salesforce.security_token)
      flash[:notice] = "Sucessfully connected to Salesforce account!"
    rescue Databasedotcom::SalesForceError => e
      @salesforce = nil
      flash[:notice] = "Error trying to connect to Salesforce! Message: " + e.message
    end
  end

  # GET /admin/salesforces/new
  def new
    @admin_salesforce = Admin::Salesforce.new
  end

  # GET /admin/salesforces/1/edit
  def edit
  end

  # POST /admin/salesforces
  def create
    @admin_salesforce = Admin::Salesforce.new(admin_salesforce_params)

    if @admin_salesforce.save
      redirect_to @admin_salesforce, notice: 'Salesforce was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /admin/salesforces/1
  def update
    if @admin_salesforce.update(admin_salesforce_params)
      redirect_to @admin_salesforce, notice: 'Salesforce was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /admin/salesforces/1
  def destroy
    @admin_salesforce.destroy
    redirect_to admin_salesforces_url, notice: 'Salesforce was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_admin_salesforce
    @admin_salesforce = Admin::Salesforce.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def admin_salesforce_params
    params.require(:admin_salesforce).permit(:username, :password, :client_id, :client_secret, :security_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: [:show, :edit, :update, :destroy]
  before_action :setup_salesforce, except: [:new]
  # GET /leads
  # GET /leads.json
  def index
    @leads = Lead.all
  end

  # GET /leads/1
  # GET /leads/1.json
  def show
  end

  # GET /leads/new
  def new
    @lead = Lead.new
  end

  # GET /leads/1/edit
  def edit
  end

  # POST /leads
  # POST /leads.json
  def create
    @lead = Lead.new(lead_params)

    respond_to do |format|
      if @lead.save
        sync_contact(@lead)
        format.html { redirect_to leads_url, notice: 'Lead was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /leads/1
  # PATCH/PUT /leads/1.json
  def update
    respond_to do |format|
      if @lead.update(lead_params)
        sync_contact(@lead)
        format.html { redirect_to leads_url, notice: 'Lead was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /leads/1
  # DELETE /leads/1.json
  def destroy
    @lead.destroy
    respond_to do |format|
      format.html { redirect_to leads_url, notice: 'Lead was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_lead
    @lead = Lead.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def lead_params
    params.require(:lead).permit(:name, :last_name, :email, :company, :job_title, :phone, :website, :salesforce_id, :salesforce_updated_at)
  end

  # Setup Salesforce connector
  def setup_salesforce
    if(@salesforce == nil)
      config = Admin::Salesforce.first
      @salesforce = Databasedotcom::Client.new(:client_id => config.client_id, :client_secret => config.client_secret)
      @salesforce.authenticate(:username => config.username, :password => config.password + config.security_token)
    end
  end

  # Sync contact
  def sync_contact (lead)
    setup_salesforce

    params = {"FirstName" => lead.name,
      "LastName" => lead.last_name,
      "Email" => lead.email,
      "Phone" => lead.phone,
      "Title" => lead.job_title,
      "OwnerId" => @salesforce.user_id}

    if lead.salesforce_id != nil && @salesforce.find("Contact", lead.salesforce_id)
      @salesforce.update("Contact", lead.salesforce_id, params)
    else
      c = @salesforce.create("Contact", params)
    c.save()
    lead.salesforce_id = c.Id
    end
    lead.salesforce_updated_at = Date.new()
    lead.save()
  end

end

app/helpers/admin/salesforces_helper.rb
module Admin::SalesforcesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/admin/salesforces/_form.html.erb
<%= form_for(@admin_salesforce, class: "pure-form") do |f| %>
<% if @admin_salesforce.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@admin_salesforce.errors.count, "error") %> prohibited from being saved:</h2>

	<ul>
		<% @admin_salesforce.errors.full_messages.each do |message| %>
		<li>
			<%= message %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="field">
	<%= f.label :username %>
	<br>
	<%= f.text_field :username %>
</div>
<div class="field">
	<%= f.label :password %>
	<br>
	<%= f.text_field :password %>
</div>
<div class="field">
	<%= f.label :client_id %>
	<br>
	<%= f.text_field :client_id %>
</div>
<div class="field">
	<%= f.label :client_secret %>
	<br>
	<%= f.text_field :client_secret %>
</div>
<div class="field">
	<%= f.label :security_token %>
	<br>
	<%= f.text_field :security_token %>
</div>
<div class="actions">
	<%= f.submit "Save", class: "pure-button button-blue"%>
</div>
<% end %>

app/views/admin/salesforces/edit.html.erb
<center>
<h1>Salesforce config</h1>

<%= render 'form' %>

<%= link_to 'Go to Leads', leads_path, class: 'pure-button button-orange' %>
</center>

app/views/admin/salesforces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admin Salesforces</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>Client</th>
      <th>Client secret</th>
      <th>Security token</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_salesforces.each do |admin_salesforce| %>
      <tr>
        <td><%= admin_salesforce.username %></td>
        <td><%= admin_salesforce.password %></td>
        <td><%= admin_salesforce.client_id %></td>
        <td><%= admin_salesforce.client_secret %></td>
        <td><%= admin_salesforce.security_token %></td>
        <td><%= link_to 'Show', admin_salesforce %></td>
        <td><%= link_to 'Edit', edit_admin_salesforce_path(admin_salesforce) %></td>
        <td><%= link_to 'Destroy', admin_salesforce, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Salesforce', new_admin_salesforce_path %>

app/views/admin/salesforces/new.html.erb
<h1>Salesforce config</h1>

<%= render 'form' %>

<%= link_to 'Go to Leads', leads_path %>

app/views/admin/salesforces/show.html.erb
<p id="notice">
	<%= notice %>
</p>

<p>
	<strong>Username:</strong>
	<%= @admin_salesforce.username %>
</p>

<p>
	<strong>Password:</strong>
	<%= @admin_salesforce.password %>
</p>

<p>
	<strong>Client:</strong>
	<%= @admin_salesforce.client_id %>
</p>

<p>
	<strong>Client secret:</strong>
	<%= @admin_salesforce.client_secret %>
</p>

<p>
	<strong>Security token:</strong>
	<%= @admin_salesforce.security_token %>
</p>

<%= link_to 'Edit', edit_admin_salesforce_path(@admin_salesforce) %> |
<%= link_to 'Leads', leads_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Leads</title>
  <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/pure/0.6.0/pure-min.css" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/leads/_form.html.erb
	<%= form_for(@lead, class: "pure-form") do |f| %>
	<% if @lead.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@lead.errors.count, "error") %> prohibited this lead from being saved:</h2>

		<ul>
			<% @lead.errors.full_messages.each do |message| %>
			<li>
				<%= message %>
			</li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<div class="field">
		<%= f.label :name %>
		<br>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :last_name %>
		<br>
		<%= f.text_field :last_name %>
	</div>
	<div class="field">
		<%= f.label :email %>
		<br>
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :company %>
		<br>
		<%= f.text_field :company %>
	</div>
	<div class="field">
		<%= f.label :job_title %>
		<br>
		<%= f.text_field :job_title %>
	</div>
	<div class="field">
		<%= f.label :phone %>
		<br>
		<%= f.text_field :phone %>
	</div>
	<div class="field">
		<%= f.label :website %>
		<br>
		<%= f.text_field :website %>
	</div>
	<div class="actions">
		<%= f.submit "Save", class: "pure-button pure-button-primary"%>
	</div>
	<% end %>

app/views/leads/edit.html.erb
<h1>Editing Lead</h1>

<%= render 'form' %>

<%= link_to 'Show', @lead %> |
<%= link_to 'Back', leads_path %>

app/views/leads/index.html.erb
<center>
	<p id="notice">
		<%= notice %>
	</p>

	<h1>Listing Leads</h1>

	<table id="leads" class="pure-table pure-table-bordered pure-table-striped">
		<thead>
			<tr>
				<th>Name</th>
				<th>Email</th>
				<th>Company</th>
				<th>Job title</th>
				<th>Phone</th>
				<th>Website</th>
				<th>Salesforce</th>
				<th colspan="1">Actions</th>
			</tr>
		</thead>

		<tbody>
			<% @leads.each do |lead| %>
			<tr>
				<td><%= link_to (lead.name + " " + lead.last_name), edit_lead_path(lead) %></td>
				<td><%= lead.email %></td>
				<td><%= lead.company %></td>
				<td><%= lead.job_title %></td>
				<td><%= lead.phone %></td>
				<td><%= lead.website %></td>
				<td><%= link_to "Link", (@salesforce.instance_url + "/" + lead.salesforce_id), target: "salesforce" %></td>
				<td><%= link_to 'Delete', lead, class: "button-red pure-button", method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
			<% end %>
		</tbody>
	</table>

	<br>

	<%= link_to 'New Lead', new_lead_path, class: "pure-button-primary pure-button" %>
	<%= link_to 'Config', "/", class: "button-light-blue pure-button" %>
</center>

app/views/leads/new.html.erb
<center>
<h1>New Lead</h1>

<%= render 'form' %>

<%= link_to 'Go to Leads', leads_path, class: "pure-button button-orange" %>
</center>

app/views/leads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lead.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @lead.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @lead.email %>
</p>

<p>
  <strong>Company:</strong>
  <%= @lead.company %>
</p>

<p>
  <strong>Job title:</strong>
  <%= @lead.job_title %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @lead.phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= @lead.website %>
</p>

<p>
  <strong>Salesforce:</strong>
  <%= @lead.salesforce_id %>
</p>

<p>
  <strong>Salesforce updated at:</strong>
  <%= @lead.salesforce_updated_at %>
</p>

<%= link_to 'Edit', edit_lead_path(@lead) %> |
<%= link_to 'Back', leads_path %>